# Generated by Django 5.0.4 on 2024-04-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_place_data_visited_place_notes_place_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='data_visited',
            new_name='date_visited',
        ),
    ]
